name: Android CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-35
            build-tools;35.0.0
            platform-tools
      - name: Gradle Build (wrapper yok)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.14.3
          arguments: >
            assembleDebug assembleRelease bundleRelease
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk/**/*.apk
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: app/build/outputs/bundle/release/*.aab
