name: Android CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      # --- Android SDK: manuel kurulum (action yok) ---
      - name: Install Android SDK cmdline-tools
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          curl -sSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
          unzip -q cmdtools.zip -d cmdline-tools-tmp
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-tmp/cmdline-tools/* cmdline-tools/latest/
          rm -rf cmdline-tools-tmp cmdtools.zip
          echo "sdk.dir=$ANDROID_SDK_ROOT" > $GITHUB_WORKSPACE/local.properties
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses

      - name: Install required SDK packages
        run: |
          set -e
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      # --- Gradle: wrapper'sız derleme ---
      - name: Gradle build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: >
            -Porg.gradle.jvmargs="-Xmx2g"
            assembleDebug assembleRelease bundleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk/**/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: app/build/outputs/bundle/release/*.aab
